
[extract_abstract]
template = "extract_abstract"
category = "document"
input_params = { text = "text" }
output_parser = "json"
[extract_abstract.llm_args]
temperature = 0
max_tokens = 500
format = "json"


[extract_title]
template = "extract_title"
category = "document"
input_params = { text = "text" }
output_parser = "json"
[extract_title.llm_args]
temperature = 0
max_tokens = 200
format = "json"
